### ISSUE TITLE
Non-Latin Character ?

### ISSUE THREAD

**Issue by hos3in** [awsmug/Questions#1]
Dear awsmug,
When i use your plug in the title of Text or Textarea changed to "?????????".
Your plugin not support of Non-Latin Character (e.g utf-8 encoding ). how can i fix this problem?

Best regards,
Hosein.

**Comment by mahype** [comment]
Hello Hosein,

thats strange. There should be no char at all in the title. Do you can show me your installation? You can send me a mail to sven@awesome.ug.

Best Regards,

Sven

**Comment by mahype** [comment]
I have changed the DB collation for the tables to utf8_general_ci. It should work now.
