### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Gioweb** [awsmug/Questions#18]
Hi, i send you  from email the italian translation file "questions-locale-it_IT.po" tnk for your wonderful plugin. 

Ciao
Giovanni

**Comment by mahype** [comment]
Hello Giovanni,

thanks a lot for that! :) I will add it in the next version of „Questions".

Greetings,

Sven

Viele Grüße,

Sven Wagener

*Awesome UG*
WordPress Plugin Factory

Krepperweg 4
40724 Hilden

Mobil +49 (0) 151 / 546 755 96
sven@awesome.ug
www.awesome.ug

2015-08-05 13:25 GMT+02:00 Gioweb <notifications@github.com>:

**Comment by Gioweb** [comment]
hi Sven, can I use Poedit to enter translations in this version? I'm doing a survey and I have to do it in Italian and I like to use your plugin. 

Ciao
Giovanni

**Comment by Gioweb** [comment]
Edit: Hi Sven, I translated with NotePad ++, but once opened with Poedit, I found the compilation errors that I solved most one that keeps me going. I send you the new file by e-mail...

**Comment by mahype** [comment]
Thank you! I have the same problem with the string at this line … And I can't import it to our translation database.

**Comment by mahype** [comment]
I solved the problem now. If you want to help in future, you can do it in our database at Transifex:

https://www.transifex.com/mahype/questions/

If you have registered, completed the registration and logged in, just open the URL above and start to translate.

I will take your translations directly into the next version of Questions.
