### ISSUE TITLE
Breaks my CEO plugin. All In One SEO Pack

### ISSUE THREAD

**Issue by ibiza69** [awsmug/Questions#19]
Hi, the your plugin is very nice and configurable, but at "All In One SEO Pack" plugin, makes dissapear the section at posts: "Social Settings". 

This section at All In One SEO Pack, it´s for sharing and indexing your posts at social networks, so you should try to fix this, so your plugin doesn´t break any option or configuration at other wordpress plugins.

**Comment by mahype** [comment]
Thanks for reporting!

I will check this and give you feedback.

**Comment by ibiza69** [comment]
Thanks Sven. We have a big survey created but cannot use it, untill this is fixed. We where about 2 hours configurating the survey and finally we couldnt use it. Hopefully you find what could be happening. If you install the ceo plugin I told you, activate social in it and go to create a post you will see under the post all the social configuration. After, install your plugin and see how that social section at post just dissapears.


Thanks for your time and underestanding.


Carlos

De:"Sven Wagener" <notifications@github.com>
Fecha:mié 12 12e ago 12e 2015 a las 14:48
Asunto:Re: [Questions] Breaks my CEO plugin. All In One SEO Pack (#19)

Thanks for reporting!

I will check this and give you feedback.

**Comment by mahype** [comment]
I'm now fixing the bug and will let you know when I'm finished.

**Comment by mahype** [comment]
I have launched the beta 19 and fixed your bug. It was an CSS conflict. Just update to beta 19. Can you check this?

**Comment by ibiza69** [comment]
Hi, just perfect, everything working fine ! 
You have GREAT support, you solved this very, very quick !
Recomended to all: https://wordpress.org/plugins/questions

**Comment by mahype** [comment]
That makes me happy! :) Hope you enjoy it!
