### ISSUE TITLE
Cookie & IP

### ISSUE THREAD

**Issue by ibiza69** [awsmug/Questions#23]
Hi, yesterday I activated the plugin with a survey and done the survey my self, to see how long the cookie expirated and 12 hours after, I can see that I can do the survey again.

Is there any way, for configurating this at the plugin? For example, our survey is from 13 to 31 august and do not want people to repeat the survey, only 1 time per person.

Hopefully there is a solution for this, if not the results would´t be reliable.

Thanks in advance!

**Comment by mahype** [comment]
Hi,

thats a kind of a problem in the internet. You can identify peoply by IP, but that normally switches after a time. Also you can setup a cookie, but it's very easy to delete your browser cookies. Lust but not least the user can change the device where he is answering.

At the moment I only have inserted the IP Check. The problem is, that most providers are switching the IP if you're reconnecting to the internet. 

I am working on to rewrite the user restrictions and adding a user restrictions API. There will also come the cookies check. But I'm searching for a library wich can check more. Maybe a propability check will help in this case (http://stackoverflow.com/questions/15966812/user-recognition-without-cookies-or-local-storage). 

I will see what I can do, but form technically point of view, there is no relieability to check people 100%. I'm sorry for that, but there would only the way to take your laptop and run thru the people in real life and ask them to answer your survey, after you have checked if the person has already answered or not ;)

I will let you know how I resolved it if I have finished the Restrictions API.

Greetings,

Sven

**Comment by mahype** [comment]
Just some notes for me:

##Browser fingerprinting
http://sklueh.de/2013/09/browser-fingerprinting-mit-javascript/
https://github.com/carlo/jquery-browser-fingerprint

**Comment by ibiza69** [comment]
Thanks again! It seems quite complex to develop. In our particular case, we normaly clean all caches before closing our PCs and turn off router by night. Next day, the router has a different IP. Anyway, I can see its a hard job, so again thank you for your time and for writing back ;)

**Comment by mahype** [comment]
Oh I forgot. There is also the way that you only allow Users of the site to answer the survey. Therefor every participiant needs a WordPress Account. The question is which people are participating your survey. If they would be ready to registrate for a survey this could be also a solution.

**Comment by ibiza69** [comment]
Hi, thanks for all the feedback. The problem is that our clients do not have a wordpress.com account.

 

One thing else, I cannot send our website thru here, as I do not want to have it exposed, but if you send me an email, I can send you the url. The problem is that with mobile devices, the answers to the questions, some of them, show cutted, do not show correct and is imposible to read. We have Samsung S4 mobile devices. Is there a solution for this?

 

Thank you!

 

 

De: Sven Wagener [mailto:notifications@github.com] 
Enviado el: viernes, 14 de agosto de 2015 11:03
Para: awsmug/Questions <Questions@noreply.github.com>
CC: ibiza69 <worldsmarketing@yahoo.es>
Asunto: Re: [Questions] Cookie & IP (#23)

 

Oh I forgot. There is also the way that you only allow Users of the site to answer the survey. Therefor every participiant needs a WordPress Account. The question is which people are participating your survey. If they would be ready to registrate for a survey this could be also a solution.

**Comment by mahype** [comment]
>The problem is that our clients do not have a wordpress.com account.

Just for your understanding. They don't need a wordpress.com account. They need an account of your WordPress installation.

> One thing else, I cannot send our website thru here, as I do not want to have it exposed, but if you send me an email, I can send you the url. 

Just send me an email to support@awesome.ug.

**Comment by ibiza69** [comment]
I´ve sended you an email with URL. Thanks !

**Comment by mahype** [comment]
OK. I have watched it an a S4 

* in Firefox which was really bad,
* in Chrome which was nearly OK,
* and on the standard Browser

As I can see, there are again problems with charts. I have to work at this for some days to figure all out. This is not so an easy topic. It's not the first time I have problems with the charts.

At the moment I'm reworking the form processing on submitting data. After that I will come back to that topic and try to get it all work. I'm sorry for that, but I need some time for this to get it perfect.

**Comment by ibiza69** [comment]
Sure Sven, thank you! 

 

It´s a lot to have you dump on this and for sure it must be difficult ;) we underestand. 

Whenever you can, I´ll be here and can keep on talking.

 

Oh! I nearly forgot, we use at Samsung s4 the standard browser, we have too Chrome, 

but we use it only a few times to check how our sites see after changing something, etc…

 

And sorry if we have so manny suggestions, we just want to give a hand :D

 

Have a very nice day ;)

 

Carlos

 

 

De: Sven Wagener [mailto:notifications@github.com] 
Enviado el: viernes, 14 de agosto de 2015 15:21
Para: awsmug/Questions <Questions@noreply.github.com>
CC: ibiza69 <worldsmarketing@yahoo.es>
Asunto: Re: [Questions] Cookie & IP (#23)

 

OK. I have watched it an a S4 

*	in Firefox which was really bad,
*	in Chrome which was nearly OK,
*	and on the standard Browser

As I can see, there are again problems with charts. I have to work at this for some days to figure all out. This is not so an easy topic. It's not the first time I have problems with the charts.

At the moment I'm reworking the form processing on submitting data. After that I will come back to that topic and try to get it all work. I'm sorry for that, but I need some time for this to get it perfect.

**Comment by mahype** [comment]
No Problem! This was good food for my thoughts ;)

**Comment by mahype** [comment]
In the next verision you can restrict visitors by choosing filtering IP, Cookies and Browser-Fingerprinting:

![edit_form_ _plugin_tests_ _wordpress_-_2015-08-18_11 34 18](https://cloud.githubusercontent.com/assets/663697/9326849/2366922e-459d-11e5-85ca-f8fc43e66a4d.png)

I have already inserted the code for it in the coming up Beta 20.

**Comment by mahype** [comment]
In the beta 20 will also come a Restrictions API.  By extending the Class Questions_Restrictions you can easy add your own restrictions. Take a look here:

https://github.com/awsmug/Questions/blob/develope/components/restrictions/base-restrictions/all-members.php

**Comment by ibiza69** [comment]
Thanks! This is all just GREAT!

 

BUT, for people that want things made easy, without touching the CODE, etc…?

 

Would you have something that will make this easy and secure?

 

And, when will come up the BETA 2.0 vers.?

 

THANKS!!

 

 

De: Sven Wagener [mailto:notifications@github.com] 
Enviado el: martes, 18 de agosto de 2015 11:41
Para: awsmug/Questions <Questions@noreply.github.com>
CC: ibiza69 <worldsmarketing@yahoo.es>
Asunto: Re: [Questions] Cookie & IP (#23)

 

In the beta 20 will also come a Restrictions API. By extending the Class Questions_Restrictions you can easy add your own restrictions. Take a look here:

https://github.com/awsmug/Questions/blob/develope/components/restrictions/base-restrictions/all-members.php

**Comment by mahype** [comment]
> BUT, for people that want things made easy, without touching the CODE, etc…?

For doing the browser fingerprint you only have to click the checkbox. But for extending the API you have to code in PHP.

 >Would you have something that will make this easy and secure?
What do you mean?

>And, when will come up the BETA 2.0 vers.?
The beta20 will come up next week. I have to add the notices like Email and text on finishing a form.

**Comment by ibiza69** [comment]
I mean, some configuration at WP Plugin, without touching the code, but hard enough for bening secure about blocking the second reound at the survey made.

 

Thanks again!

 

De: Sven Wagener [mailto:notifications@github.com] 
Enviado el: martes, 18 de agosto de 2015 12:10
Para: awsmug/Questions <Questions@noreply.github.com>
CC: ibiza69 <worldsmarketing@yahoo.es>
Asunto: Re: [Questions] Cookie & IP (#23)

 

BUT, for people that want things made easy, without touching the CODE, etc…?

For doing the browser fingerprint you only have to click the checkbox. But for extending the API you have to code in PHP.

Would you have something that will make this easy and secure?
What do you mean?

And, when will come up the BETA 2.0 vers.?
The beta20 will come up next week. I have to add the notices like Email and text on finishing a form.

**Comment by mahype** [comment]
>  hard enough for bening secure about blocking the second reound at the survey made

If somebody wants to get the second round, he will get it if he is an expert in faking forms. As I said: There is no way to get it secure by 100% because there is no technical way to identify another person sitting on a computer.

What we are doing is building up barriers for users who want to fake. All in all it will just decrease the percentage of users who wants to fake you. At this place we have three barriers now. I don't know more ways to get it harder because I think there are only this three ways to identify people.

**Comment by ibiza69** [comment]
Thanks! Yes, inded is MORE than enough!


Best Support ;) Thanks again !!

De:"Sven Wagener" <notifications@github.com>
Fecha:mar 18 18e ago 18e 2015 a las 12:47
Asunto:Re: [Questions] Cookie & IP (#23)

hard enough for bening secure about blocking the second reound at the survey made

If somebody wants to get the second round, he will get it if he is an expert in faking forms. As I said: There is no way to get it secure by 100% because there is no technical way to identify another person sitting on a computer.

What we are doing is building up barriers for users who want to fake. All in all it will just decrease the percentage of users who wants to fake you. At this place we have three barriers now. I don't know more ways to get it harder because I think there are only this three ways to identify people.

**Comment by mahype** [comment]
You're welcome! :)

**Comment by ibiza69** [comment]
Hi again!

 

Today I found another small bug. When you visit the results or questions at website, thru mobile, the ppal website menu opens by it self. When the page loads the menu comes open. It only happens at this sections. Hopefully this helps ;)

 

 

De: Sven Wagener [mailto:notifications@github.com] 
Enviado el: martes, 18 de agosto de 2015 14:05
Para: awsmug/Questions <Questions@noreply.github.com>
CC: ibiza69 <worldsmarketing@yahoo.es>
Asunto: Re: [Questions] Cookie & IP (#23)

 

You're welcome! :)

**Comment by mahype** [comment]
Can you give me an example? I don't understand what you mean.

**Comment by ibiza69** [comment]
Do you remember the URLs of our site, that I passed you thru email? If you check with your mobile in one of those the website menu at mobiles instead of being normally closed so you can press on it when you need, it shows directly opened.


Hopefully I've explained better, sorry ;)


Thanks!

De:"Sven Wagener" <notifications@github.com>
Fecha:mié 19 19e ago 19e 2015 a las 14:41
Asunto:Re: [Questions] Cookie & IP (#23)

Can you give me an example? I don't understand what you mean.
