### ISSUE TITLE
Wrong floating labels in metaboxes

### ISSUE THREAD

**Issue by arkonisus** [awsmug/Questions#24]
Please take a look at the screenshot ;)
![bildschirmfoto 2015-08-18 um 20 47 05](https://cloud.githubusercontent.com/assets/7242966/9339467/8aa38a08-45ea-11e5-9bfb-c268276cafb0.png)

**Comment by mahype** [comment]
Yes ;) This is already fixed in beta20. This version will come in the next week. Thank you for reporting!
