### ISSUE TITLE
Doesn't initialise correctly when installed as network plugin on multisite installation

### ISSUE THREAD

**Issue by qubika** [awsmug/Questions#3]
Firstly, great plugin - very slick and I like it a lot.

I've worked around this problem, but just wanted to let you know in case it's an easy fix.

I installed the Questions plugin into a multisite installation then enabled it for the network.  TheSurvey menu option appeared correctly in the sub-site, but when trying to save a new survey, it cleared the details and only a blank post was saved.

After enabling the debug log, I found that the following was being output ('multisite' is the db name):

[21-May-2015 14:46:08 UTC] WordPress database error Table '...multisite_21_questions_questions' doesn't exist for query INSERT INTO `multisite_21_questions_questions` (`questions_id`,`question`,`sort`,`type`) VALUES ('294','','1','OneChoice') made by edit_post, wp_update_post, wp_insert_post, do_action('save_post'), call_user_func_array, Questions_Admin->save_survey, Questions_Admin->save_survey_postdata

So it appeared that the database wasn't being correctly initialised when the network enable was chosen. If I disable the plugin at the network level then enable on the site, it works fine.

Looks like an extra hook might be required for network enable, or the readme.txt updated to say that it should only be enabled at a site level.

**Comment by bueltge** [comment]
I think it is important, that also work in multisite environment. I think,  the right way is,  that each site get extra tables for the questions, so that each blog can use the plugin with custom questions and settings.

**Comment by mahype** [comment]
Yes of cause! I will take a look at the table creation in the next days.

**Comment by mahype** [comment]
The Database should be work. I have fixed and tested it with a multisite installation. Now the tables for the blog will be created if the admin was visited his site admin the first time after it was activated the network wide.

Can you give me feedback if it works correct on your installation now?

Thnak you!

**Comment by qubika** [comment]
Hi,

I just tried installing the latest patch but it seemed worse I'm afraid.  I
think the database tables were created successfully, but the Survey editor
appeared to be broken so I couldn't create or edit surveys.

Note that since my server doesn't have internet access then I had to delete
the old plugin before installing the latest one.

I've now rolled back to the previous version - don't have time to analyse
what the errors are I'm afraid.

Thanks.

**Comment by mahype** [comment]
Oh im very sorry for that. I didn't had those problems on my installation. Would it be posssible that you can make me a screenshot of your broken editor? I would like to fix it as soon as possible.

**Comment by qubika** [comment]
I'll create a new wordpress instance and try to repeat the steps since my
previous update was on a 'live' site - will be in touch when I get this
done.

In the Add new Survey screen, the Drop your Element here text wasn't shown
in the box and none of the elements could be dragged onto the panel.   My
guess would be either an html element wasn't set properly or the javascript
was broken but there were no obvious javascript errors.

Hope this helps and I'll be in touch once I've set up a test site.

**Comment by mahype** [comment]
We changed the JS of the Drag&Drop area in our last update because we wanted that you can drag and drop your survey element at every place and it should be added at the end anymore. So we also removed the text there where you have to drop and changed the JS.

Do you already tried to empty your browser cache? Maybe you are using the old scripts.
