### ISSUE TITLE
constantly get the are "open answers" in survey

### ISSUE THREAD

**Issue by chuckgeorgo** [awsmug/Questions#4]
i checked to make sure settings are correct in all questions.

yet i still get a red banner ONLY AT THE TOP saying "there are open answers"

NO red banners show up in any of the questions.

survey is at: http://www.infragardmd.org/?questions=2015-imma-member-survey 

thanks

**Comment by mahype** [comment]
Hello,

sorry but I can't see your survey. Maybe it's because I'm not logged in to your page?

Can you check this or publis the survey?

Greetings,

Sven

**Comment by mahype** [comment]
I also answered you at wordpress.org in the support forums.
