### ISSUE TITLE
Export survey file is with ??????

### ISSUE THREAD

**Issue by kupisait** [awsmug/Questions#5]
Export survey file is with ?????? characteristicts How to resolve it?

**Comment by mahype** [comment]
Hello,

can you send me an example of the file? I need more information for solving your problem.

Greetings,

Sven

**Comment by kupisait** [comment]
![print](https://cloud.githubusercontent.com/assets/12824705/8079674/e7cff8d6-0f6e-11e5-8abe-8a1891b36e55.JPG)
Text is cyrillik. I this there is some problem in utf-8 exporting.

**Comment by kupisait** [comment]
what is going on?

**Comment by bueltge** [comment]
Do you also examples of your questions, answers. Please check also the `wp-config.php` for the constant `DB_CHARSET`.  Also a todo on your side, check the database and the questions tables, are all in unicode charset, collate? The export from the plugin is in your charset, what you define in your install.

```php
$charset = 'UTF-8'
header( "Content-Type: Content-Type: text/csv; charset=" . $charset );
```

@mahype 
Maybe we should use the `get_bloginfo( 'blog_charset' );` for the setting in each blog.

**Comment by mahype** [comment]
Yes I will implement it today and it will come with the beta 15.

**Comment by bueltge** [comment]
@mahype But this is not helpful for the problem from @kupisait . I think his problem is other topic. I see forward for feedback from his side to my questions. But currently I can export unicode strings in my tests.

**Comment by kupisait** [comment]
All database for plug in ae in utf-8 , conf file is utf-8

**Comment by kupisait** [comment]
I made new test installation and again it doesnt work......................

**Comment by kupisait** [comment]
Thank you for "quick" and "usefull" help

**Comment by mahype** [comment]
I am sorry, but I've been a bit busy with customer projects the last two days. I made an update for the charset output. Pleas use the latest version of Github to test.

**Comment by mahype** [comment]
The UTF8 export problem is also solved now.
