### ISSUE TITLE
Enhance body_class() 

### ISSUE THREAD

**Issue by bueltge** [awsmug/Questions#6]
It would be helpful, that Questions add a custom class to the `body_class` function to identifier pages, posts, there use a shortcode etc. from questions. Makes much easier to identifier the form and makes possible to custom format.

Pseude-code
```php
add_filter( 'body_class', 'custom_body_class' );
function custom_body_class($classes) {
	
	$classes[] = 'question-' . get_question_id() ;
	
	return $classes;
}
```

**Comment by mahype** [comment]
Great point! I will add this and give you feedback if it's integrated.

**Comment by mahype** [comment]
It's added! :)

**Comment by bueltge** [comment]
:+1:

**Comment by bueltge** [comment]
But is not included on pages, if you use the shortcode in a page, or?

**Comment by mahype** [comment]
Yes you are right. This are pages. But you can layout the forms by using the Ids and classes from the from. Or what would you recommend?

**Comment by bueltge** [comment]
Maybe you can check, the shortcode is active and enhance the body class. But maybe a overhead. Alternative was it fine, that questions create the front end view, similar a page with the shortcode.

**Comment by mahype** [comment]
Yes I could. I will take it to my "ideas" list and maybe we have a really good reason later to implement it.
